{% set name = "xarray-dataclasses" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xarray_dataclasses-{{ version }}.tar.gz
  sha256: 5ea909a960e26d9022851d962fac1378e64ff2095b3e0dddfa3afa7911a92cae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - poetry
  run:
    - numpy >=1.22,<2.0.0a0
    - python >=3.8
    - typing-extensions >=4.0,<5.0
    - xarray >=2022.3,<2023.0
    
test:
  imports:
    - xarray_dataclasses
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/astropenguin/xarray-dataclasses/
  summary: xarray data creation made easy by dataclass
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
