{% set name = "xarray-dataclasses" %}
{% set version = "1.9.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xarray_dataclasses-{{ version }}.tar.gz
  sha256: e5e88e10622b2bcb4db6087d636327f6e0311ae66fa10e94ea571805ed6937ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - python >={{ python_min }}
    - numpy >=1.22,<3.0
    - typing-extensions >=4.0
    - xarray >=2022.3,<2025.0

test:
  imports:
    - xarray_dataclasses
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/astropenguin/xarray-dataclasses/
  summary: xarray data creation made easy by dataclass
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jdblischak
    - LucaMarconato
    - melonora
    - timtreis
